### ISSUE TITLE
please convert xlsx to tsv 

### ISSUE THREAD

**Issue by jhpoelen** [millerse/US-National-Parasite-Collection#2]
GloBI doesn't support xlsx . . . the format is not quite suitable for data archives: proprietary format and hard to digest by programs. So, suggest to save the xlsx as a tsv (tab separated values) and update the globi.json accordingly.

**Comment by millerse** [comment]
Done

**Comment by jhpoelen** [comment]
@millerse just curious - I am noticing that in ```globi.json```, the file http://invertebrates.si.edu/pdfs/NationalParasiteCollection_29-May-2014.txt is used. So, this means that GloBI is using a file that is external to the github repository. Would it be an idea to copy the file to the github repo as is and ```globi.json``` to it? In the citation, you can then mention where you got the file from and we'll have a independently archived copy with doi of it in Zenodo. 

Curious to hear your thoughts on this.

**Comment by jhpoelen** [comment]
ps thanks for all the hard work and being patient with me!

**Comment by millerse** [comment]
@jhpoelen There is always the hope that the Entomology department will update the collection and that will be captured easily.  I assumed that the tsv files are used as a copy of the dataset for archive purpose.  Hope that makes sense.

**Comment by jhpoelen** [comment]
Ah yes, that makes total sense. Perhaps we should figure out a way to indicate the original source and their archived copies. . . . something to think about.
